version: "3.9"

services:
  backend:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: laravel-backend
    volumes:
      - './.:/var/www/html'
      - './.env:/var/www/html/.env' # .env dosyasını container içine bağla
    ports:
      - "8082:8000"
    command: php artisan serve --host=0.0.0.0 --port=8000  
    env_file:
      - ./.env
    networks:
      - backend-network
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:14
    container_name: postgres-db
    env_file:
      - ./.env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $DB_USERNAME -d $DB_DATABASE"]
      interval: 5s
      timeout: 5s
      retries: 10
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend-network
    ports:
      - "${DB_PORT:-5432}:5432"

networks:
  backend-network:
    driver: bridge

volumes:
  postgres_data:
    driver: local
